### ISSUE TITLE
uncaught exception in Coinapult transaction history when you have more than 20 items

### ISSUE THREAD

**Issue by arichnad** [mycelium-com/wallet#251]
To reproduce, you must have more than 20 items in your Coinapult transaction history.

Scroll down to the bottom of the 20 item list and see this uncaught exception:

```
uncaught exception
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.add(Collections.java:928)
	at android.widget.ArrayAdapter.add(ArrayAdapter.java:179)
	at com.mycelium.wallet.activity.main.TransactionHistoryFragment$Wrapper.appendCachedData(TransactionHistoryFragment.java:431)
	at com.commonsware.cwac.endless.EndlessAdapter$AppendTask.onPostExecute(EndlessAdapter.java:315)
	at android.os.AsyncTask.finish(AsyncTask.java:636)
	at android.os.AsyncTask.access$500(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

I suppose it's probably the Collections.unmodifiableList in CoinapultAccount.java, but Coinapult doesn't seem to be working on mycelium testnet, so I couldn't verify this.

**Comment by Giszmo** [comment]
Guess I fixed it in our internal branch fixCoinapultScrolling

**Comment by DanielWeigl** [comment]
Got fixed in the meantime
