### ISSUE TITLE
sentRequest failed IO Exception. java.io.IOExeption: closed

### ISSUE THREAD

**Issue by thuannv** [mycelium-com/wallet#312]
I checkout the library and integrated it into my app. But, It happened to me that the response body stream was closed and it was an error as the log below:

11-10 15:30:51.333 22819-29589/com.app I/Wapi: Wapi getVersionEx finished (1609ms)
11-10 15:30:51.334 22819-29589/com.app I/Wapi: toSend = {"branch":"android","currentVersion":"1.4.35","locale":"en"}
11-10 15:30:51.334 22819-29589/com.app I/Wapi: response.toString() = Response{protocol=http/1.1, code=200, message=OK, url=https://mws7.mycelium.com/wapi/wapi/getVersionEx}
11-10 15:30:51.336 22819-29588/com.app I/Wapi: Wapi queryTransactionInventory finished (1631ms)
11-10 15:30:51.337 22819-29588/com.app I/Wapi: toSend = {"version":1,"addresses":["17gSCU4eP97xJDd1T47ZwdK3JKg6aJfBPJ","14FqZC2DY5d8MgdqFTSKKduhZ9wBdNAZxB","1NGJGoJV4vCTjz7PZD9YKbnhqrqdfhQ54n","1ArzVhnZSVaqFL7xtBz5qckWXULSmD7f9","14K8jh6rbJR97VBA2X5GJDQVjLLMphe41B","1N8A3ZoZ2yqW2YGHtjJGuwqScXPruzsvWh","1EuwkwawZxQc8xiATChb5u1ZQzeHsC6vhp","114so2hd3i2N4LYvbZNgfj3RGrifRv4q58","1MNQLzYtmEwzAQPzW5nWfLL3M1sjrCC3QF","1BEQV4haS4rKZDyiqXa9Nd8GMcVxAATa6x","1DqDUMmj8DaVNsuKtd4LinAqCGFAhALUf8","1ATefguEDG8LEfYiDKrKXwzCtyHG4EaeTJ","1GNArMQNuTJpBRjYviCrpPSKQkh7KaAbBs","16mj3Uk2658SqaKuDEFucwEaeozKaybM5s","19L5GmbeubGkJ2EefdWeuDhz1E5wLs3iwx","1BBX9UiKm1XqdXTuk1XerzkrYWVhCECEx1","1PyPP4uVaSvNT4uyvn9R89c1usrUexKZb9","19hgAkiHG6YjMGLcdDkcCXb4s7oRavaM9o","1MgqiBPSq2tadCKrWFhdS2PVoo7crtq46","1k6oNdrmfa5MTxvKD7Z88TphvoQ2xe331","1PyL12HyZDTyUhv8vr8NFajLtmNURAAcJQ","1G1ttK75UPQARUxq9fvFjyTRk3HdJwwG5Y","19sC8r98qi3yfqvvwGycH8eHTEUpKKhHLZ","1B8R6dLTGmueVgAbrUsDGECoRteDM5uQx6","12hMnqaB8L5YJpGceHPj9E4N7ZSk5DShhX","1KnEWCZuDQpZqQjbysbdc9hhxrbhHRc29E","1K6mqApB2ksi22dYuXA9TAJ43tTdWjidmB","1PstrWdUXWK7BSbj7249Aah7gbyzejru3p","144e292aXbZvUPqckipiDVnZBL9Ndu3oCg","1PfeQYRdfD8NmRX5cGz5wcFw4KvYRwCt9M","12NMHRYtr4KR61n9x4yZApgAczMQnSq13j","1CXTuBfcXPxZeirBbr1jgsrdfeP7A2Syaf","16XHhgAzFRw5GmNQ8MmUua2tZJXiBjKBCu","1C8WYDmFxV29U43psYMcom9RNvKh9tVdXw","19Y3h1fsJYxg5CUt8mrEi8smUJgz6kC2J9","18QUkjkD94uTCF3GnP1BVikieJBgZM3Q5U","19iy5pNdq4oPZb8iFH3Kxzm3TUzUtVPPVL","14WwfoqPFKbwAofHvdPdeirqV5LFmrU4r6","1F1tzXn1ss2kb8XgNfjCPmCYmmjdnbBJg8","192u65GEhyH3GVf1njzzVxYrfjPxWtft7N"],"limit":1000}
11-10 15:30:51.337 22819-29588/com.app I/Wapi: response.toString() = Response{protocol=http/1.1, code=200, message=OK, url=https://mws7.mycelium.com/wapi/wapi/queryTransactionInventory}
11-10 15:30:51.361 22819-29588/com.app I/Wapi: response.body().string() = {"errorCode":0,"r":{"height":438189,"txIds":[]}}
11-10 15:30:51.368 22819-29589/com.app I/Wapi: response.body().string() = {"errorCode":0,"r":{"versionNumber":"2.8.5","versionMessage":"Update available","directDownload":"https://wallet.mycelium.com/contact.html"}}
11-10 15:30:51.399 22819-29588/com.app E/Wapi: sendRequest failed IO exception.
                                                                                  java.io.IOException: closed
                                                                                      at okio.RealBufferedSource$1.read(RealBufferedSource.java:367)
                                                                                      at java.io.InputStreamReader.read(InputStreamReader.java:233)
                                                                                      at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.loadMore(ReaderBasedJsonParser.java:153)
                                                                                      at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:1855)
                                                                                      at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:571)
                                                                                      at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602)
                                                                                      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
                                                                                      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2632)
                                                                                      at com.mycelium.wapi.api.WapiClient.sendRequest(WapiClient.java:77)
                                                                                      at com.mycelium.wapi.api.WapiClient.queryTransactionInventory(WapiClient.java:209)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.doDiscoveryForAddresses(Bip44Account.java:335)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.doDiscovery(Bip44Account.java:329)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.discovery(Bip44Account.java:291)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.doSynchronization(Bip44Account.java:272)
                                                                                      at com.mycelium.wapi.wallet.SynchronizeAbleWalletAccount.synchronize(SynchronizeAbleWalletAccount.java:75)
                                                                                      at com.mycelium.wapi.wallet.WalletManager$Synchronizer.synchronize(WalletManager.java:821)
                                                                                      at com.mycelium.wapi.wallet.WalletManager$Synchronizer.run(WalletManager.java:780)
                                                                                      at java.lang.Thread.run(Thread.java:818)
11-10 15:30:51.399 22819-29588/com.app E/Wapi: Server connection failed with error code: 3
                                                                                  com.mycelium.wapi.api.WapiException: Wapi error code: 3
                                                                                      at com.mycelium.wapi.api.WapiResponse.getResult(WapiResponse.java:47)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.doDiscoveryForAddresses(Bip44Account.java:336)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.doDiscovery(Bip44Account.java:329)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.discovery(Bip44Account.java:291)
                                                                                      at com.mycelium.wapi.wallet.bip44.Bip44Account.doSynchronization(Bip44Account.java:272)
                                                                                      at com.mycelium.wapi.wallet.SynchronizeAbleWalletAccount.synchronize(SynchronizeAbleWalletAccount.java:75)
                                                                                      at com.mycelium.wapi.wallet.WalletManager$Synchronizer.synchronize(WalletManager.java:821)
                                                                                      at com.mycelium.wapi.wallet.WalletManager$Synchronizer.run(WalletManager.java:780)
                                                                                      at java.lang.Thread.run(Thread.java:818)
11-10 15:30:51.400 22819-29589/com.app E/Wapi: sendRequest failed IO exception.
                                                                                  java.io.IOException: closed
                                                                                      at okio.RealBufferedSource$1.read(RealBufferedSource.java:367)
                                                                                      at java.io.InputStreamReader.read(InputStreamReader.java:233)
                                                                                      at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.loadMore(ReaderBasedJsonParser.java:153)
                                                                                      at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:1855)
                                                                                      at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:571)
                                                                                      at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602)
                                                                                      at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
                                                                                      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2632)
                                                                                      at com.mycelium.wapi.api.WapiClient.sendRequest(WapiClient.java:77)
                                                                                      at com.mycelium.wapi.api.WapiClient.getVersionInfoEx(WapiClient.java:263)
                                                                                      at com.mycelium.wallet.api.AsynchronousApi$5.callFunction(AsynchronousApi.java:138)
                                                                                      at com.mycelium.wallet.api.AsynchronousApi$SynchronousFunctionCaller.run(AsynchronousApi.java:156)
                                                                                      at java.lang.Thread.run(Thread.java:818)

So, how could I handle this error or should I have to add any additional conditions to overcome this issue? 

Thanks.

**Comment by DanielWeigl** [comment]
Hello,

Im not sure what the error is, sounds like a connection issue. 

But to be honest, I would not recommend to use our library in a bigger-than-hobby project right now, because we are on it to deprecate it. Dont expect major updates to the lib. We are working on a new wallet internally that will use other bitcoin libraries, like bitcoinj.

**Comment by thuannv** [comment]
Hello,

Thanks for response to me. In honest I am working on a secure call & messaging app in need to use bitcoin for credit. Thus, I use the Mycelium library for integrating bitcoin transfer to my app. But, when I used it with configuration "prodnet" or "testnet" it suddently closed connection and the exception was as I posted above.

If possible, could you please recommend me any solution for this issue?

Thanks.

**Comment by Giszmo** [comment]
As Daniel said, please use something else. BitcoinJ is what we will migrate to. As you can see, wapi depends on our servers, too, so even if you are fine with not getting updates, your app depending on our closed source servers running should be enough to not go that route.
